# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=128, unique=True)),
                ('g_id', models.CharField(max_length=128)),
                ('c_num', models.IntegerField()),
                ('c_total_price', models.FloatField()),
                ('c_is_delete', models.BooleanField(default=0)),
            ],
        ),
    ]
