# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-22 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='u_id',
            field=models.CharField(max_length=128),
        ),
    ]
