# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-22 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20190122_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=128)),
                ('g_id', models.CharField(max_length=128)),
                ('c_num', models.IntegerField()),
                ('c_total_price', models.FloatField()),
            ],
        ),
    ]
