# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-22 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_carthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='carthistory',
            name='o_id',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
