# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=128, unique=True)),
                ('u_name', models.CharField(max_length=64, verbose_name='用户名')),
                ('u_phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('u_password', models.CharField(max_length=128, verbose_name='密码')),
            ],
        ),
    ]
