# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-22 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=128)),
                ('p_name', models.CharField(max_length=64)),
                ('p_address', models.CharField(max_length=256)),
                ('p_phone', models.CharField(max_length=32)),
            ],
        ),
    ]
