# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-22 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.CharField(max_length=128, unique=True, verbose_name='订单号')),
                ('u_id', models.CharField(max_length=128, verbose_name='买家ID')),
                ('g_id', models.CharField(max_length=128, verbose_name='商品ID')),
                ('o_num', models.IntegerField(verbose_name='数量')),
                ('o_date', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('o_message', models.CharField(max_length=128, verbose_name='留言')),
                ('o_total_price', models.FloatField(verbose_name='总价')),
                ('o_name', models.CharField(max_length=64, verbose_name='收件人')),
                ('o_address', models.CharField(max_length=128, verbose_name='收件地址')),
                ('o_phone', models.CharField(max_length=32, verbose_name='联系电话')),
                ('o_status', models.IntegerField(verbose_name='订单状态')),
                ('o_is_delete', models.BooleanField(default=False, verbose_name='是否删除订单')),
            ],
        ),
    ]
