# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-22 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='g_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='o_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='o_num',
        ),
        migrations.RemoveField(
            model_name='order',
            name='o_phone',
        ),
    ]
