# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-22 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190122_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='o_address',
        ),
    ]
