# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=128, verbose_name='买家ID')),
                ('g_id', models.CharField(max_length=128, verbose_name='商品ID')),
                ('comment', models.CharField(max_length=256, verbose_name='评价')),
                ('com_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_id', models.CharField(max_length=128, verbose_name='书本ID')),
                ('u_id', models.CharField(max_length=128, verbose_name='卖家ID')),
                ('g_c_id', models.CharField(max_length=128, verbose_name='评论ID')),
                ('g_name', models.CharField(max_length=64, verbose_name='书名')),
                ('g_price', models.FloatField(verbose_name='价格')),
                ('g_stock', models.IntegerField(default=82, verbose_name='库存')),
                ('g_image', models.CharField(max_length=128, verbose_name='图片')),
                ('g_author', models.CharField(max_length=128, verbose_name='作者')),
                ('g_sale', models.IntegerField(default=18, verbose_name='销量')),
                ('g_type', models.IntegerField(verbose_name='类型')),
            ],
        ),
    ]
