# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190121_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='g_sale',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_stock',
            field=models.IntegerField(default=100, verbose_name='库存'),
        ),
    ]
