# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190121_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='g_sale',
            field=models.IntegerField(verbose_name='销量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_stock',
            field=models.IntegerField(verbose_name='库存'),
        ),
    ]
